vincentale_repertoire:
    resource: "@VincentaleRepertoireBundle/Resources/config/routing.yml"
    prefix:    /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

vincentale_contact_view:
    path: /view/{id}
    defaults: { _controller: VincentaleUserBundle:Contact:view }
    requirements:
        id: \d+

vincentale_contact_add:
    path: /view/{id}/add
    defaults: { _controller: VincentaleUserBundle:Contact:add }
    requirements:
        id: \d+

vincentale_contact_del:
    path: /view/{id}/del
    defaults: { _controller: VincentaleUserBundle:Contact:del }
    requirements:
        id: \d+

vincentale_contact_display:
    path: /profile/contacts
    defaults: { _controller: VincentaleUserBundle:Contact:displayContacts }

vincentale_contact_search:
    path: /search
    defaults: { _controller: VincentaleUserBundle:Contact:search }