<?php

namespace Vincentale\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return un tableau d'Users dont User.username LIKE % @param %
     *
     * @param $partialUsername
     * @return array
     */
    public function findByUsernameLike($partialUsername) {
        return $this->_em->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName,'a')
            ->where('a.username LIKE :pUsername')
            ->setParameter('pUsername','%'.$partialUsername.'%')
            ->getQuery()
            ->getResult();
    }
}
